# Generated by Django 3.2.9 on 2021-11-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, choices=[('KG', 'kg'), ('LTR', 'Ltr'), ('GM', 'Gm'), ('ML', 'mL')], max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('total_stock', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='banner-6.png', null=True, upload_to='images')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
